[package]
name = "quirc"
version = "0.1.0"
authors = ["Dave Hylands <dhylands@gmail.com>"]

[dependencies]
libc = "0.2"
mjpeg-sys = { path = "mjpeg-sys" }
quirc-sys = { path = "quirc-sys" }

[dev-dependencies]
rscam = "0.5.3"
rustc-serialize = "0.3"
sdl = "0.3.6"
time = "0.1.35"

